/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONTROLER.CadastrarControler;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author vinir
 */
public class CadastrarTelaView extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaTelaView
     */
    public CadastrarTelaView() {

        initComponents();
        this.setLocationRelativeTo(null); // Centraliza a janela na tela
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public JButton getCadastrar() {
        return Cadastrar;
    }

    public void setCadastrar(JButton Cadastrar) {
        this.Cadastrar = Cadastrar;
    }

    public JButton getCadastrar1() {
        return Cadastrar1;
    }

    public void setCadastrar1(JButton Cadastrar1) {
        this.Cadastrar1 = Cadastrar1;
    }

    public JLabel getNome() {
        return Nome;
    }

    public void setNome(JLabel Nome) {
        this.Nome = Nome;
    }

    public JLabel getFundo() {
        return fundo;
    }

    public void setFundo(JLabel fundo) {
        this.fundo = fundo;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public void setLblId(JLabel lblId) {
        this.lblId = lblId;
    }

    public JLabel getLblId1() {
        return lblId1;
    }

    public void setLblId1(JLabel lblId1) {
        this.lblId1 = lblId1;
    }

    public JLabel getLblId2() {
        return lblId2;
    }

    public void setLblId2(JLabel lblId2) {
        this.lblId2 = lblId2;
    }

    public JLabel getLblId3() {
        return lblId3;
    }

    public void setLblId3(JLabel lblId3) {
        this.lblId3 = lblId3;
    }

    public JLabel getLblId4() {
        return lblId4;
    }

    public void setLblId4(JLabel lblId4) {
        this.lblId4 = lblId4;
    }

    public JLabel getLblId5() {
        return lblId5;
    }

    public void setLblId5(JLabel lblId5) {
        this.lblId5 = lblId5;
    }

    public JLabel getLblId6() {
        return lblId6;
    }

    public void setLblId6(JLabel lblId6) {
        this.lblId6 = lblId6;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getTxtEstadoCivil() {
        return txtEstadoCivil;
    }

    public void setTxtEstadoCivil(JTextField txtEstadoCivil) {
        this.txtEstadoCivil = txtEstadoCivil;
    }

    public JTextField getTxtGenero() {
        return txtGenero;
    }

    public void setTxtGenero(JTextField txtGenero) {
        this.txtGenero = txtGenero;
    }

    public JTextField getTxtNascimento() {
        return txtNascimento;
    }

    public void setTxtNascimento(JTextField txtNascimento) {
        this.txtNascimento = txtNascimento;
    }

    public JTextField getTxtNomeCompleto() {
        return txtNomeCompleto;
    }

    public void setTxtNomeCompleto(JTextField txtNomeCompleto) {
        this.txtNomeCompleto = txtNomeCompleto;
    }

    public JTextField getTxtSangue() {
        return txtSangue;
    }

    public void setTxtSangue(JTextField txtSangue) {
        this.txtSangue = txtSangue;
    }

    public JTextField getTxtTelefone() {
        return txtTelefone;
    }

    public void setTxtTelefone(JTextField txtTelefone) {
        this.txtTelefone = txtTelefone;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        lblId1 = new javax.swing.JLabel();
        lblId2 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        lblId3 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        lblId4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblId5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        lblId6 = new javax.swing.JLabel();
        txtSangue = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        Cadastrar1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("Cadastro");
        lblId.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 250, 80));

        txtNascimento.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        txtNascimento.setForeground(new java.awt.Color(255, 0, 0));
        txtNascimento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 140, 30));

        lblId1.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblId1.setForeground(new java.awt.Color(255, 255, 255));
        lblId1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId1.setText("Data de Nascimento:");
        getContentPane().add(lblId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblId2.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblId2.setForeground(new java.awt.Color(255, 255, 255));
        lblId2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId2.setText("Genero:");
        getContentPane().add(lblId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtGenero.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        txtGenero.setForeground(new java.awt.Color(255, 0, 0));
        txtGenero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 40, -1));

        lblId3.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblId3.setForeground(new java.awt.Color(255, 255, 255));
        lblId3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId3.setText("Estado Civil:");
        getContentPane().add(lblId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtEstadoCivil.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        txtEstadoCivil.setForeground(new java.awt.Color(255, 0, 0));
        txtEstadoCivil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, -1));

        lblId4.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblId4.setForeground(new java.awt.Color(255, 255, 255));
        lblId4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId4.setText("Email:");
        getContentPane().add(lblId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        txtEmail.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 0, 0));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 360, -1));

        lblId5.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblId5.setForeground(new java.awt.Color(255, 255, 255));
        lblId5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId5.setText("Telefone:");
        getContentPane().add(lblId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        txtTelefone.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(255, 0, 0));
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 230, -1));

        Nome.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        Nome.setForeground(new java.awt.Color(255, 255, 255));
        Nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nome.setText("Nome Completo:");
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtNomeCompleto.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        txtNomeCompleto.setForeground(new java.awt.Color(255, 0, 0));
        txtNomeCompleto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 510, -1));

        lblId6.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        lblId6.setForeground(new java.awt.Color(255, 255, 255));
        lblId6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId6.setText("Tipo Sanguineo:");
        getContentPane().add(lblId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        txtSangue.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        txtSangue.setForeground(new java.awt.Color(255, 0, 0));
        txtSangue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtSangue, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 70, -1));

        Cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        Cadastrar.setForeground(new java.awt.Color(255, 0, 0));
        Cadastrar.setText("Voltar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 60, -1));

        Cadastrar1.setBackground(new java.awt.Color(255, 255, 255));
        Cadastrar1.setForeground(new java.awt.Color(255, 0, 0));
        Cadastrar1.setText("Cadastrar");
        Cadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telaConsulta.jpg"))); // NOI18N
        fundo.setText("jLabel1");
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -10, 951, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
               PaginaInicialTelaView objInicialTelaView = new PaginaInicialTelaView();
        objInicialTelaView.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_CadastrarActionPerformed

    private void Cadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar1ActionPerformed
        CadastrarControler objcadastrarcontrole = new CadastrarControler(this);
        objcadastrarcontrole.cadastrarDoador();
        getTxtNomeCompleto().setText("");
        getTxtEmail().setText("");
        getTxtSangue().setText("");
        getTxtNascimento().setText("");
        getTxtTelefone().setText("");
        getTxtEstadoCivil().setText("");
        getTxtGenero().setText("");

    }//GEN-LAST:event_Cadastrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarTelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarTelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarTelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarTelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarTelaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Cadastrar1;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblId2;
    private javax.swing.JLabel lblId3;
    private javax.swing.JLabel lblId4;
    private javax.swing.JLabel lblId5;
    private javax.swing.JLabel lblId6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtSangue;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
