/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author vinir
 */
public class PaginaInicialTelaView extends javax.swing.JFrame {

    /**
     * Creates new form Pagina_InicialView
     */
    public PaginaInicialTelaView() {
        initComponents();
        this.setLocationRelativeTo(null); // Centraliza a janela na tela
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public void fecharTelaInicialView() {
        dispose();
        LoginTelaView tela1 = new LoginTelaView();
        tela1.setVisible(true);
    }

    public void abrirMeusDadosView() {
        RemoverDoadorTelaView objMeusDadosView = new RemoverDoadorTelaView();
        objMeusDadosView.setVisible(true);
        dispose();
    }

    public void abrirAgendarDocao() throws SQLException {
        AgendarDoacaoTelaView objAgendarDoacaoView = new AgendarDoacaoTelaView();
        objAgendarDoacaoView.setVisible(true);
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnAgendarDoacao = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnRemover1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Bem-Vindo!");

        jButton2.setBackground(new java.awt.Color(236, 4, 4));
        jButton2.setFont(new java.awt.Font("Gadugi", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Meus Dados");
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sangue Solidário");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 300, 40));

        btnSair.setBackground(new java.awt.Color(236, 4, 4));
        btnSair.setFont(new java.awt.Font("Gadugi", 3, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 90, 30));

        btnRemover.setBackground(new java.awt.Color(236, 4, 4));
        btnRemover.setFont(new java.awt.Font("Gadugi", 3, 18)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover.setText("Atualizar");
        btnRemover.setBorder(null);
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 170, 40));

        btnAgendarDoacao.setBackground(new java.awt.Color(236, 4, 4));
        btnAgendarDoacao.setFont(new java.awt.Font("Gadugi", 3, 18)); // NOI18N
        btnAgendarDoacao.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarDoacao.setText("Agendar Doação");
        btnAgendarDoacao.setBorder(null);
        btnAgendarDoacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgendarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarDoacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgendarDoacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 170, 40));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Bem-Vindo ");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 290, 90));

        btnCadastrar.setBackground(new java.awt.Color(236, 4, 4));
        btnCadastrar.setFont(new java.awt.Font("Gadugi", 3, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(null);
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, 40));

        btnRemover1.setBackground(new java.awt.Color(236, 4, 4));
        btnRemover1.setFont(new java.awt.Font("Gadugi", 3, 18)); // NOI18N
        btnRemover1.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover1.setText("Remover");
        btnRemover1.setBorder(null);
        btnRemover1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemover1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tela2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        fecharTelaInicialView();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
 AtualizarDoadorTelaView objatualizardoadortelaview = new AtualizarDoadorTelaView();
        objatualizardoadortelaview.setVisible(true);
   this.dispose();

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAgendarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarDoacaoActionPerformed
        AgendarDoacaoTelaView objagendardoacaoview = null;
        try {
            objagendardoacaoview = new AgendarDoacaoTelaView();
        } catch (SQLException ex) {
            Logger.getLogger(PaginaInicialTelaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        objagendardoacaoview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgendarDoacaoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
CadastrarTelaView objcadastratelaview = new CadastrarTelaView();
        objcadastratelaview.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnRemover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover1ActionPerformed
RemoverDoadorTelaView objdoadortelaview = new RemoverDoadorTelaView();
        objdoadortelaview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRemover1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicialTelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicialTelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicialTelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicialTelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicialTelaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarDoacao;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnRemover1;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
